load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "main",
    srcs = ["main.rs"],
    data = ["//angular/projects/build-scan-web"],
    deps = [
        "//build-scan/server/db/src:db",
        "//build-scan/server/graphql/src:graphql",
        "//build-scan/server/ingest/src:ingest",
        "//build-scan/server/service/src:service",
        "@crates//:axum",
        "@crates//:juniper_axum",
        "@crates//:tokio",
        "@crates//:tower-http",
        "@crates//:tracing",
        "@crates//:tracing-subscriber",
    ],
)
