{
  "type": "record",
  "name": "JavaToolchain_1_0",
  "namespace": "com.gradle.scan.eventmodel.gradle.java",
  "fields": [
    { "name": "id", "type": "long" },
    { "name": "version", "type": ["null", "string"], "default": null },
    { "name": "vendor", "type": ["null", "string"], "default": null },
    { "name": "runtimeName", "type": ["null", "string"], "default": null },
    { "name": "runtimeVersion", "type": ["null", "string"], "default": null },
    { "name": "vmName", "type": ["null", "string"], "default": null },
    { "name": "vmVersion", "type": ["null", "string"], "default": null },
    { "name": "vmVendor", "type": ["null", "string"], "default": null },
    { "name": "arch", "type": ["null", "string"], "default": null }
  ]
}
