load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "ingest",
    srcs = ["lib.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//server/service/src:service",
        "@crates//:axum",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:tokio",
        "@crates//:uuid",
    ],
)
