{
  "type": "record",
  "name": "MvnResourceUsageIndexedNormalizedSamples_1_0",
  "namespace": "com.gradle.scan.eventmodel.maven.resourceusage",
  "fields": [
    {
      "name": "indices",
      "type": [
        "null",
        { "type": "array", "items": { "type": "array", "items": "int" } }
      ],
      "default": null
    },
    {
      "name": "samples",
      "type": ["null", { "type": "array", "items": "bytes" }],
      "default": null
    },
    { "name": "max", "type": "long" }
  ]
}
