load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "service",
    srcs = ["lib.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//build-scan/lib/src:lib",
        "//build-scan/lib/src:models",
        "//build-scan/server/db/src:db",
        "@crates//:hex",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:tracing",
    ],
)
