load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "graphql",
    srcs = ["lib.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//build-scan/server/domain/src:domain",  # keep
        "//build-scan/server/graphql/relay/src:relay",  # keep
        "//build-scan/server/service/src:service",  # keep
        "@crates//:axum",
        "@crates//:juniper",
        "@crates//:juniper_axum",
        "@crates//:serde_json",
    ],
)
