load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "graphql",
    srcs = ["lib.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//build-scan/server/db/src:db",
        "//build-scan/server/graphql/relay/src:relay",
        "@crates//:axum",
        "@crates//:juniper",
        "@crates//:juniper_axum",
        "@crates//:serde_json",
        "@crates//:sqlx",
    ],
)
