{
  "type": "enum",
  "name": "MvnTestSelectionFailureType_1",
  "namespace": "com.gradle.scan.eventmodel.maven.pts",
  "symbols": [
    "BUILD_AGENT_INTERNAL_ERROR",
    "BUILD_AGENT_NETWORK_UNAVAILABLE",
    "BUILD_AGENT_OFFLINE",
    "CLIENT_UNAUTHORIZED",
    "SERVICE_EXTENSION_DISABLED",
    "SERVICE_INSUFFICIENT_CHANGE_HISTORY",
    "SERVICE_INTERNAL_ERROR",
    "SERVICE_PROCESSING_TIMEOUT",
    "SERVICE_UNPROCESSED_EXECUTIONS",
    "UNSUPPORTED_TEST_TASK",
    "TEST_TARGET_INPUTS_INDETERMINABLE",
    "UNSUPPORTED_CLIENT"
  ]
}
