{
  "type": "record",
  "name": "PluginApplied_1_0",
  "namespace": "com.gradle.scan.eventmodel.gradle",
  "fields": [
    { "name": "projectPath", "type": ["null", "string"], "default": null },
    { "name": "pluginClassName", "type": ["null", "string"], "default": null },
    { "name": "inferredVersion", "type": ["null", "string"], "default": null },
    { "name": "inferredId", "type": ["null", "string"], "default": null },
    {
      "name": "codeSourceType",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.plugin.PluginCodeSourceType_1"
      ],
      "default": null
    }
  ]
}
