{
  "type": "record",
  "name": "ResourceUsage_2_0",
  "namespace": "com.gradle.scan.eventmodel.gradle",
  "fields": [
    {
      "name": "timestamps",
      "type": ["null", { "type": "array", "items": "bytes" }],
      "default": null
    },
    {
      "name": "buildProcessCpu",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "buildChildProcessesCpu",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "allProcessesCpuSum",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    { "name": "allProcessesCpu", "type": ["null", "bytes"], "default": null },
    {
      "name": "buildProcessMemory",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "buildChildProcessesMemory",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "allProcessesMemory",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    { "name": "totalSystemMemory", "type": ["null", "long"], "default": null },
    {
      "name": "diskReadSpeed",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "diskWriteSpeed",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "networkDownloadSpeed",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "networkUploadSpeed",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "processes",
      "type": [
        "null",
        {
          "type": "array",
          "items": "com.gradle.scan.eventmodel.gradle.resourceusage.Process_1_0"
        }
      ],
      "default": null
    },
    {
      "name": "topProcessesByCpu",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageIndexedNormalizedSamples_1_0"
      ],
      "default": null
    },
    {
      "name": "topProcessesByMemory",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.resourceusage.ResourceUsageIndexedNormalizedSamples_1_0"
      ],
      "default": null
    }
  ]
}
