{
  "type": "record",
  "name": "TaskInputsImplementation_1_0",
  "namespace": "com.gradle.scan.eventmodel.gradle",
  "fields": [
    { "name": "id", "type": "long" },
    { "name": "classLoaderHash", "type": ["null", "bytes"], "default": null },
    {
      "name": "actionClassLoaderHashes",
      "type": ["null", { "type": "array", "items": "bytes" }],
      "default": null
    },
    {
      "name": "actionClassNames",
      "type": ["null", { "type": "array", "items": "string" }],
      "default": null
    }
  ]
}
