{
  "type": "record",
  "name": "MvnBuildCacheRemoteConnectorConfig_1_0",
  "namespace": "com.gradle.scan.eventmodel.maven.buildcache",
  "fields": [
    {
      "name": "authenticationType",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.maven.buildcache.MvnBuildCachingRemoteAuthenticationType_1"
      ],
      "default": null
    },
    { "name": "allowInsecureProtocol", "type": "boolean" },
    { "name": "useExpectContinue", "type": "boolean" },
    { "name": "storeEnabled", "type": "boolean" },
    { "name": "authenticated", "type": "boolean" },
    { "name": "allowUntrustedServer", "type": "boolean" },
    { "name": "useEdgeDiscovery", "type": "boolean" }
  ]
}
