{
  "type": "record",
  "name": "MvnBuildCacheRemoteConnector_1_0",
  "namespace": "com.gradle.scan.eventmodel.maven.buildcache",
  "fields": [
    {
      "name": "disabledReasonCategory",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.maven.buildcache.MvnBuildCachingDisabledReasonCategory_1"
      ],
      "default": null
    },
    { "name": "disabledReason", "type": ["null", "string"], "default": null },
    { "name": "storeEnabled", "type": ["null", "boolean"], "default": null },
    { "name": "url", "type": ["null", "string"], "default": null },
    { "name": "authenticated", "type": ["null", "boolean"], "default": null },
    {
      "name": "allowUntrustedServer",
      "type": ["null", "boolean"],
      "default": null
    }
  ]
}
