load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "main",
    srcs = ["main.rs"],
    deps = [
        "//proxy/config/src:config",  # keep
        "//proxy/db/src:db",  # keep
        "//proxy/format/src:format",  # keep
        "//proxy/graphql/src:graphql",  # keep
        "//proxy/service/src:service",  # keep
        "@crates//:axum",
        "@crates//:base64",
        "@crates//:chrono",
        "@crates//:juniper_axum",
        "@crates//:reqwest",
        "@crates//:serde_json",
        "@crates//:tokio",
        "@crates//:tracing",
        "@crates//:tracing-subscriber",
        "@crates//:uuid",
    ],
)
