{
  "type": "record",
  "name": "ComponentDependency_1_0",
  "namespace": "com.gradle.scan.eventmodel.gradle.dependencies",
  "fields": [
    {
      "name": "requested",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.dependencies.ComponentIdentity"
      ],
      "default": null
    },
    { "name": "componentId", "type": ["null", "int"], "default": null },
    {
      "name": "attempted",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.dependencies.ComponentIdentity"
      ],
      "default": null
    },
    {
      "name": "attemptedReason",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.dependencies.ComponentSelectionReason_1"
      ],
      "default": null
    },
    {
      "name": "failure",
      "type": [
        "null",
        "com.gradle.scan.eventmodel.gradle.exception.ExceptionTree_1_0"
      ],
      "default": null
    }
  ]
}
