load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "db",
    srcs = ["lib.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "//build-scan/server/db/migrations/src:migrations",  # keep
        "//build-scan/server/domain/src:domain",  # keep
        "@crates//:anyhow",
        "@crates//:chrono",
        "@crates//:serde_json",
        "@crates//:sqlx",
        "@crates//:uuid",
    ],
)
