load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//docs:astro/package_json.bzl", astro_bin = "bin")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "srcs",
    srcs = glob([
        "src/**",
        "public/**",
        "astro.config.mjs",
        "package.json",
        "tsconfig.json",
    ]),
)

astro_bin.astro_test(
    name = "check",
    args = ["check"],
    chdir = package_name(),
    data = [
        ":node_modules",
        ":srcs",
    ],
)

astro_bin.astro(
    name = "build",
    srcs = [
        ":node_modules",
        ":srcs",
    ],
    args = ["build"],
    chdir = package_name(),
    out_dirs = ["dist"],
)
