name: Deploy
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            common --compilation_mode=opt
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Log in to GHCR
        uses: docker/login-action@a0d57b8e43b6ef1cca20559d68cec2227e63fccd
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push All Images
        run: bazel query 'kind("oci_push rule", //...)' | xargs -n 1 bazel run --compilation_mode=opt
