name: Deploy
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: bazel-contrib/setup-bazel@63ef5dcbe9527cf2996e060ddb3a09b78b3bf258
        with:
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            common --compilation_mode=opt
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Log in to GHCR
        uses: docker/login-action@da5b89b92c1be57a07eeed1334a0728b94145654
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push All Images
        run: bazel query 'kind("oci_push rule", //...)' | xargs -n 1 bazel run --compilation_mode=opt
