name: Deploy
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: bazel-contrib/setup-bazel@7ff4255e941f2652381d81e4e6e2b4965680091d
        with:
          bazelisk-cache: true
          bazelrc: |
            common --config=ci
            common --compilation_mode=opt
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Log in to GHCR
        uses: docker/login-action@9fe7774c8f8ebfade96f0a62aa10f3882309d517
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push All Images
        run: bazel query 'kind("oci_push rule", //...)' | xargs -n 1 bazel run --compilation_mode=opt
